[relaychain]
default_command = "polkadot"
chain = "paseo-local"

[[relaychain.nodes]]
name = "alice"
validator = true
ws_port = 9944

[[relaychain.nodes]]
name = "bob"
validator = true
ws_port = 9955

[[parachains]]
id = 5134

[parachains.collator]
name = "charlie"
ws_port = 9988
command = "parachain-template-node"
